### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by SkyrisBactera** [akamensky/argparse#9] opened 2018-01-12 05:42 UTC
If you use an argument and pass no value, the go program panics with ```panic: runtime error: slice bounds out of range```. 
PoC:
```go
parser := argparse.NewParser("download", "Downloads URL matching provided string")
// Create string flag
searchQuery = parser.String("q", "query", &argparse.Options{Required: true, Help: "URL to download"})
// Parse input
err := parser.Parse(os.Args)
if err != nil {
	// In case of error print error and print usage
	// This can also be done by passing -h or --help flags
	fmt.Println(err.Error())
	fmt.Print(parser.Usage(parser))
}
```

```bash
go run main.go -q
```

**Comment by akamensky** [comment] 2018-01-12 06:46
Right on, seems I missed the array boundaries check there. Should be an easy fix

**Comment by akamensky** [comment] 2018-01-12 07:02
@SkyrisBactera Added the fix for this issue along with test case. Closing. Feel free to re-open if you feel the issue is not yet resolved

**Closed by akamensky** 2018-01-12 07:02 UTC
Labels: bug
